default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: camaar_development

test:
  <<: *default
  database: camaar_test

production:
  <<: *default
  database: camaar_production
  username: <%= ENV['CAMAAR_DATABASE_USERNAME'] %>
  password: <%= ENV['CAMAAR_DATABASE_PASSWORD'] %>
